services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  be:
    build: ./api
    environment:
      MODE: production
      PORT: 8080
      DATABASE_URL: postgresql://postgres:admin123@postgres/postgres
    container_name: be
    image: img:be
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  
  fr:
    build:
      context: ./webapp
      args:
        VITE_API_URL: http://51.20.85.189:8080/api
    container_name: fr
    image: img:fr
    ports:
      - "80:80"
    depends_on:
      - be
volumes:
  postgres-data:
